_testform_homepage:
    path:     /testform
    defaults: { _controller: JhekasoftTestformBundle:Default:index }

_testform_restart:
    path:     /testform/restart
    defaults: { _controller: JhekasoftTestformBundle:Default:restart }

_testform_save_personal_data:
    path:     /testform/save-personal-data
    defaults: { _controller: JhekasoftTestformBundle:Default:savePersonalData }

_testform_save_questions:
    path:     /testform/save-questions
    defaults: { _controller: JhekasoftTestformBundle:Default:saveQuestions }

_testform_questions:
    path:     /testform/questions
    defaults: { _controller: JhekasoftTestformBundle:Default:questions }

_testform_win:
    path:     /testform/win
    defaults: { _controller: JhekasoftTestformBundle:Default:win }

_testform_exported_document:
    path:     /api/stream
    defaults: { _controller: JhekasoftTestformBundle:Default:exportedDocument }
